services:
  db:
    image: postgres:16
    container_name: sso_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Dhaka
    networks:
      - sso_network
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    build: ./redis
    container_name: sso_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
        - TZ=Asia/Dhaka
    ports:
      - "6379:6379"
    networks:
      - sso_network

  backend:
    build: ./backend
    container_name: sso_backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - sso_network
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      -  TZ=Asia/Dhaka

#  frontend:
#    build: ./frontend
#    container_name: sso_frontend
#    command: sh -c "npm install && npm start"
#
#    ports:
#      - "3000"
#    networks:
#      - sso_network
#    depends_on:
#      - backend

  nginx:
    build: ./nginx
    container_name: sso_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
#      - frontend
    environment:
        - TZ=Asia/Dhaka
    networks:
      - sso_network


volumes:
  postgres_data:
  redis_data:

networks:
  sso_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.20.0/27